name = "BAHH MINIGAMES 1.1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "897137dcd3ee3f371eeee28f756dc3b096e0683b64829a87148d1431e5ad4d4f"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
