name = "BAHH MINIGAMES 1.1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e8a164a801d7b727b24b7c942701a1ee16eb647ded1bc6b2869446804ffa872"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
