name = "BAHH MINIGAMES 1.1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae7d2d5db22c4bcc432921e30f3bd59604a3b956eb9c2d14ef402b2aca0c7541"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
